trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  MAVEN_OPTS: '-Xmx1024m'

steps:
# Paso 1: Clonar el repositorio
- task: UseGitVersion@5
  displayName: 'Clonar repositorio'

# Paso 2: Instalar Google Chrome
- powershell: |
    Write-Host "Descargando Google Chrome"
    Invoke-WebRequest -Uri "https://dl.google.com/chrome/install/latest/chrome_installer.exe" -OutFile "chrome_installer.exe"
    Write-Host "Instalando Google Chrome"
    Start-Process -FilePath ".\chrome_installer.exe" -ArgumentList "/silent /install" -NoNewWindow -Wait
  displayName: "Instalar Google Chrome"

# Paso 3: Configurar ChromeDriver
- powershell: |
    Write-Host "Descargando la última versión de ChromeDriver"
    $chromeDriverVersion = Invoke-RestMethod -Uri "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"
    $chromeDriverUrl = "https://chromedriver.storage.googleapis.com/$chromeDriverVersion/chromedriver_win32.zip"
    Invoke-WebRequest -Uri $chromeDriverUrl -OutFile "chromedriver.zip"
    Expand-Archive -Path "chromedriver.zip" -DestinationPath ".\chromedriver"
    Write-Host "Moviendo ChromeDriver al PATH del sistema"
    Move-Item -Path ".\chromedriver\chromedriver.exe" -Destination "C:\Windows\System32\" -Force
  displayName: "Configurar ChromeDriver"

# Paso 4: Ejecutar pruebas Maven
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean test'
    options: '-Dtest=AllTests#testLoginTest'
    javaHomeOption: 'JDKVersion'
    jdkVersion: '1.11'
    mavenVersionOption: 'Default'
    publishJUnitResults: true

# Paso 5: Publicar resultados de pruebas
- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/surefire-repots/*.xml'
    testRunTitle: 'Resultados de Pruebas Selenium'
